In [12]:
# LIBRARY IMPLEMENTATION
import numpy as np
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
Decision_Tree = tree.DecisionTreeClassifier()
X = np.load('X_train.npy')
X = X.reshape(60000,784)
X = X / 255.0
y = np.load('y_train.npy')
print(y)

X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.8,random_state=42)
Decision_Tree.fit(X_train,y_train)

y_pred = Decision_Tree.predict(X_test)
print("Accuracy :" ,accuracy_score(y_test,y_pred))



[5 0 4 ... 5 6 8]
Accuracy : 0.8671666666666666


In [13]:
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [5]:
# ENTROPY CALCULATION
import numpy as np
def Entropy(labels):
    entropy = 0
    size = labels.size
    numbers = {1:0,2:0,3:0,4:0,5:0,6:0,7:0,8:0,9:0,0:0}
    for x in labels:
        numbers[x] += 1
    for key in numbers.keys():
        entropy +=(numbers[key]/float(size)) *np.log2(numbers[key]/float(size))
    return entropy

In [ ]:
def compute_entropy_threshold(data , index,labels):
    entropy_labels = Entropy(labels)
    computed_values = []
    feature = data[:,index]
    for I in range(0,feature.size):
        arr1 = np.empty(0)
        arr2 = np.empty(0)
        if (feature[I] not in computed_values):
            computed_values.append(feature[I])
            for j in range(0,labels.size):
                if (feature[j] < feature[I]):
                    arr1 = np.append(arr1,labels[j])
                else:
                    arr2 = np.append(arr2,labels[j])
            entropy_drop = entropy_labels - ((arr1.size)/labels.size)*Entropy(arr1) - ((arr1.size)/labels.size)*Entropy(arr2)
            if (I == 0):
                max_info = entropy_drop
            if (entropy_drop > max_info):
                threshold = feature[I]
                split_arr1 = arr1
                split_arr2 = arr2

                max_info = entropy_drop
            
            

    


    



In [19]:
a = np.empty(0)
a = np.append(a,1)
print(a)

[1.]
